//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
 using System;
 using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
namespace ProjectCoffee.Models
{
   
    
    public partial class Product
    {
        public string NameProduct { get; set; }
        [Required(ErrorMessage ="NameProduct is Required"]
        public int Price { get; set; }
        public byte[] imag { get; set; }
    }
}
