//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectCoffee.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {


        [Required(AllowEmptyStrings = false, ErrorMessage = "First Name is Required.")]
        [Display(Name = "First Name: ")]
        public string FirstName { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Last Name is Required.")]
        [Display(Name = "Last Name: ")]
        public string LastName { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "BirthDate is Required.")]
        [Display(Name = "BirthDate: ")]
        [DataType(DataType.Date)]
        public System.DateTime BirthDate { get; set; }
        [Key]
        [Required(AllowEmptyStrings = false, ErrorMessage = "UserName is Required.")]
        [Display(Name = "Username : ")]
        public string Username { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Password is Required.")]
        [Display(Name = "Password: ")]
        [DataType(DataType.Password)]
        public string Password { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Confirm Password is Required.")]
        [DataType(DataType.Password)]
        [Compare("Password", ErrorMessage = "Password and confirm should be same.")]
        public string ConfirmPassword { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Email is Required.")]
        [DataType(DataType.EmailAddress)]
        [Display(Name = "Email: ")]
        public string Email { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "PhoneNumber is Required.")]
        [Display(Name = "PhoneNumber: ")]
        [DataType(DataType.PhoneNumber)]
        public int PhoneNumber { get; set; }
    }
}
